#!/bin/bash
#===============================================================================
#
#          FILE:  glsgrep.sh
# 
#         USAGE:  ./glsgrep.sh 
# 
#   DESCRIPTION:  
# 
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:   (), 
#       COMPANY:  
#       VERSION:  1.0
#       CREATED:  26.02.2014 09:53:08 CET
#      REVISION:  ---
#===============================================================================


# identify files holding glossary definitions

FILES=''
while read LINE ; do

    if [[ "$LINE" =~ loadglsentries\{([^}]+)\} ]]; then
        FILES="$FILES ${BASH_REMATCH[1]}"
    fi

done < <(grep 'loadglsentries' *.tex)

if [[ $# -eq 0 ]]; then
    # use clipboard content as search term
    if [[ -x xsel ]]; then
        SEARCHTERM=$(xsel -b)
        echo "searching for '$SEARCHTERM'"
    fi
else
    SEARCHTERM=$1
fi


egrep $SEARCHTERM --color=auto $FILES

