#!/bin/bash
#===============================================================================
#
#          FILE:  mkv
# 
#         USAGE:  ./mkv
# 
#   DESCRIPTION:  markdown viewer
# 
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Georg Wassen (georg.wassen@googlemail.com), 
#       COMPANY:  
#       VERSION:  1.0
#       CREATED:  11.12.2013 08:52:26 CET
#      REVISION:  ---
#===============================================================================

# Utilities:
#  markdown (F18:discount)
#     $ markdown test.md > test-markdown.html
#     - generates only the html body content
#     - writes special characters (eg umlaut ä) 1:1 to the output
#  markdown2 (F18:python-markdown2)
#     $ markdown2 test.md > test-markdown2.html
#     - generates only the html body content
#     - writes special characters (eg umlaut ä) 1:1 to the output
#     - does not know tables
#  discount-makepage (F18:discount)
#  discount-mkd2html (F18:discount)

discount-mkd2html -header "<meta charset='utf-8'>" $@



