#!/bin/bash
#===============================================================================
#
#          FILE:  texgrep
# 
#         USAGE:  ./texgrep
# 
#   DESCRIPTION:  grep in TEX files
# 
#       OPTIONS:  ---
#  REQUIREMENTS:  ---
#          BUGS:  ---
#         NOTES:  ---
#        AUTHOR:  Georg Wassen (georg.wassen@googlemail.com), 
#       COMPANY:  
#       VERSION:  1.0
#       CREATED:  10.12.2013 12:57:06 CET
#      REVISION:  ---
#===============================================================================

function usage() {
    echo
    echo "Grep in *.tex files"
    echo "Usage:"
    echo "  $(basename $0) [parameters] [<regex>]"
    echo "    (may use egrep regular expressions)"
    echo "    If no <regex> is provided, using X11 clipboard content (xsel -b)"
    echo "    e.g.: $(basename $0) Pellizzoni[0-9]*Predictable"
    echo "  Parameters: "
    echo "    -cN --context=N        Show N lines of context around matches (default: 2)"
    echo "    -h  --help             Show this help"
    echo "    -x  --exclude-comments Exclude searching in commented (deactivated) parts"
    echo
}

ARGS=$(getopt -o 'c::hx' -l 'context::,help,exclude-comments' -- "$@")   # parse parameters and store normalized string in $ARGS
eval set -- "$ARGS";                           # set parameters to preprocessed string $ARGS

PARAM_SEARCHTERM=''
PARAM_CONTEXT=''
PARAM_PREFIX=''

while [[ $# -gt 0 ]]; do
    #echo "1='$1'"
    case "$1" in
        -h|--help)
            usage
            exit
            ;;
        -c|--context)
            PARAM_CONTEXT='-2'
            if [[ $2 ]]; then
                PARAM_CONTEXT="-$2"
            fi
            shift
            ;;
        -x|--exclude-comments)
            PARAM_PREFIX='^[^%]*'
            ;;
        --)
            # ignore
            ;;
        *)
            # set as search term
            PARAM_SEARCHTERM="$1"
            ;;
    esac
    shift
done

if [[ -z $PARAM_SEARCHTERM ]]; then
    # no parameter: use clipboard buffer
    PARAM_SEARCHTERM=$(xsel -b)
fi


echo "PARAM_SEARCHTERM='$PARAM_SEARCHTERM'"
#echo "PARAM_CONTEXT='$PARAM_CONTEXT'"
#echo "PARAM_PREFIX='$PARAM_PREFIX'"

# first grep: search for all occurences of $SEARCHTERM
#             using $PREFIX (if set) to exclude commented lines
#             color filename and line number, but unset coloring of match 
# second grep: color matches to $SEARCHTERM (without $PREFIX)
GREP_COLORS='mt=' egrep --color=always -ni $PARAM_CONTEXT "$PARAM_PREFIX$PARAM_SEARCHTERM" *.tex | egrep --color=always -e '' -e $PARAM_SEARCHTERM

